version: "3.9"

services:
  mosquitto-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"

  mqtt-client-a:
    build: ./
    command: python protocols/MQTT/clients/mqtt_client_a.py
    depends_on:
      - mosquitto-broker

  mqtt-client-b:
    build: ./
    command: python protocols/MQTT/clients/mqtt_client_b.py
    depends_on:
      - mosquitto-broker

