services:
  mqtt-client-a:
    environment:
      - MEASUREMENT_SUFFIX=_chaos

  mqtt-client-b:
    environment:
      - MEASUREMENT_SUFFIX=_chaos

  coap-client:
    environment:
      - MEASUREMENT_SUFFIX=_chaos

  coap-server:
    environment:
      - MEASUREMENT_SUFFIX=_chaos

  http-client:
    environment:
      - MEASUREMENT_SUFFIX=_chaos

  pumba:
    image: ghcr.io/alexei-led/pumba:latest
    container_name: pumba-netem
    restart: "no"
    depends_on:
      - mosquitto-broker
      - mqtt-client-a
      - mqtt-client-b
      - coap-server
      - coap-client
      - http-server
      - http-client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --log-level
      - info
      - netem
      - --tc-image
      - gaiadocker/iproute2
      - --duration
      - 30m
      - delay
      - --time
      - "120"
      - --jitter
      - "30"
      - --correlation
      - "20"
      - re2:.*(mosquitto-broker|mqtt-client-a|mqtt-client-b|coap-server|coap-client|http-server|http-client).*
