services:

  # MQTT
  mosquitto-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./protocols/MQTT/mosquitto.conf:/mosquitto-broker/mosquitto.conf

  mqtt-client-a:
    build: ./
    command: python protocols/MQTT/clients/mqtt_client_a.py
    depends_on:
      - mosquitto-broker

  mqtt-client-b:
    build: ./
    command: python protocols/MQTT/clients/mqtt_client_b.py
    depends_on:
      - mosquitto-broker

# HTTP
  http-server:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./protocols/HTTP/server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/var/www/uploads/upload

  http-client:
    build: .
#    command: python protocols/HTTP/client/http_client.py
    command: python -m protocols.HTTP.client.http_client
    depends_on:
      - http-server
    volumes:
      - ./output:/app/output

# CoAP
  coap-server:
    build: .
    command: python protocols/CoAP/server/coap_server.py
    ports:
      - "5683:5683/udp"

  coap-client:
    build: .
    command: python protocols/CoAP/client/coap_client.py
    depends_on:
      - coap-server